version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"

  database:
    hostname: database
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_DATABASE=wnioski
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - ./docker/mysql/storage:/var/lib/mysql
